-- Addon Config

HSK_TITLE   = "HunterSwissKnife";
HSK_VERSION = "v1.0";

SLASH_HUNTERSWISSKNIFE1 = "/hsk";
SLASH_HUNTERSWISSKNIFE2 = "/hunterswissknife";

HSK_RED = "|cFFFF0000"
HSK_GRE = "|cFF00FF00"
HSK_BLU = "|cFF0000FF"
HSK_YEL = "|cFFFFFF00"
HSK_CYA = "|cFF00FFFF"
HSK_ORA = "|cFFFF8C00"
HSK_PIN = "|cFFFF69B4"
HSK_DEF = "|r"
