-- Addon Config

HUNTERSWISSKNIFE_TITLE = "HunterSwissKnife";
HUNTERSWISSKNIFE_VESRION = "v1.0";

SLASH_HUNTERSWISSKNIFE1 = "/hsk";
SLASH_HUNTERSWISSKNIFE2 = "/hunterswissknife";

RED_C = "|cFFFF0000"
GRE_C = "|cFF00FF00"
BLU_C = "|cFF0000FF"
YEL_C = "|cFFFFFF00"
CYA_C = "|cFF00FFFF"
ORA_C = "|cFFFF8C00"
PIN_C = "|cFFFF69B4"
DEF_C = "|r"
